"""create table user tokens

Revision ID: ff90497128f8
Revises: 399822c109bd
Create Date: 2025-02-26 15:32:44.679798

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff90497128f8"
down_revision: Union[str, None] = "399822c109bd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "usertokens",
        sa.Column("token", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_usertokens_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_usertokens")),
    )
    op.create_index(
        op.f("ix_usertokens_token"), "usertokens", ["token"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usertokens_token"), table_name="usertokens")
    op.drop_table("usertokens")
    # ### end Alembic commands ###
